name: retwho
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <=3.0.5'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  http: ^0.13.4
  jwt_decoder: ^2.0.1
  fl_chart: ^0.55.1
  get_storage: ^2.0.3

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  integration_test:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo/

